"""initial schema

Revision ID: 405edcc14072
Revises: 
Create Date: 2026-07-30 04:42:57.542991+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '405edcc14072'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('graph_version', sa.Integer(), nullable=False),
    sa.Column('graph_status', sa.String(length=24), nullable=False),
    sa.Column('graph_error', sa.Text(), nullable=True),
    sa.Column('days_per_week', sa.Integer(), nullable=False),
    sa.Column('minutes_per_session', sa.Integer(), nullable=False),
    sa.Column('daily_review_cap', sa.Integer(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('target_retention', sa.Float(), nullable=False),
    sa.Column('recovery_aware', sa.Boolean(), nullable=False),
    sa.Column('last_decay_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subjects'))
    )
    op.create_table('changesets',
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('request_text', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('base_version', sa.Integer(), nullable=False),
    sa.Column('result_version', sa.Integer(), nullable=True),
    sa.Column('validation_error', sa.Text(), nullable=True),
    sa.Column('suggestion_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_changesets_subject_id_subjects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_changesets'))
    )
    with op.batch_alter_table('changesets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_changesets_subject_id'), ['subject_id'], unique=False)

    op.create_table('concept_nodes',
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_key', sa.String(length=200), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=24), nullable=False),
    sa.Column('is_satellite', sa.Boolean(), nullable=False),
    sa.Column('introduced_in_version', sa.Integer(), nullable=False),
    sa.Column('removed_in_version', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_concept_nodes_subject_id_subjects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_concept_nodes')),
    sa.UniqueConstraint('subject_id', 'name_key', name='uq_concept_nodes_subject_name_key')
    )
    with op.batch_alter_table('concept_nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_concept_nodes_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index('ix_concept_nodes_subject_live', ['subject_id', 'deleted_at'], unique=False)

    op.create_table('diagnostic_sessions',
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('graph_version', sa.Integer(), nullable=False),
    sa.Column('max_items', sa.Integer(), nullable=False),
    sa.Column('min_items', sa.Integer(), nullable=False),
    sa.Column('confidence_target', sa.Float(), nullable=False),
    sa.Column('asked_count', sa.Integer(), nullable=False),
    sa.Column('final_mean_confidence', sa.Float(), nullable=True),
    sa.Column('stop_reason', sa.String(length=32), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_diagnostic_sessions_subject_id_subjects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diagnostic_sessions'))
    )
    with op.batch_alter_table('diagnostic_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diagnostic_sessions_subject_id'), ['subject_id'], unique=False)

    op.create_table('graph_suggestions',
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('proposed_ops', sa.JSON(), nullable=False),
    sa.Column('node_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('dedupe_key', sa.String(length=200), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_graph_suggestions_subject_id_subjects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_graph_suggestions'))
    )
    with op.batch_alter_table('graph_suggestions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_graph_suggestions_dedupe_key'), ['dedupe_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_graph_suggestions_subject_id'), ['subject_id'], unique=False)

    op.create_table('lesson_plans',
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('graph_version', sa.Integer(), nullable=False),
    sa.Column('coverage_at_creation', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_lesson_plans_subject_id_subjects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lesson_plans'))
    )
    with op.batch_alter_table('lesson_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lesson_plans_subject_id'), ['subject_id'], unique=False)

    op.create_table('lessons',
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('node_id', sa.String(length=36), nullable=True),
    sa.Column('unit_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('markdown', sa.Text(), nullable=False),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.Column('cache_key', sa.String(length=200), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_lessons_subject_id_subjects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lessons')),
    sa.UniqueConstraint('cache_key', name='uq_lessons_cache_key')
    )
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lessons_node_id'), ['node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lessons_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lessons_unit_id'), ['unit_id'], unique=False)

    op.create_table('study_sessions',
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('scheduled_for', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('planned_minutes', sa.Integer(), nullable=False),
    sa.Column('retrieval_minutes', sa.Integer(), nullable=False),
    sa.Column('review_node_ids', sa.JSON(), nullable=False),
    sa.Column('new_node_ids', sa.JSON(), nullable=False),
    sa.Column('unit_ids', sa.JSON(), nullable=False),
    sa.Column('deferred_node_ids', sa.JSON(), nullable=False),
    sa.Column('projected_coverage', sa.Float(), nullable=False),
    sa.Column('recovery_score', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('calendar_event_id', sa.String(length=200), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_study_sessions_subject_id_subjects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_sessions'))
    )
    with op.batch_alter_table('study_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_sessions_scheduled_for'), ['scheduled_for'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_sessions_subject_id'), ['subject_id'], unique=False)

    op.create_table('changeset_ops',
    sa.Column('changeset_id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('op_type', sa.String(length=24), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.Column('result_node_ids', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changeset_id'], ['changesets.id'], name=op.f('fk_changeset_ops_changeset_id_changesets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_changeset_ops'))
    )
    with op.batch_alter_table('changeset_ops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_changeset_ops_changeset_id'), ['changeset_id'], unique=False)

    op.create_table('concept_edges',
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('prereq_id', sa.String(length=36), nullable=False),
    sa.Column('node_id', sa.String(length=36), nullable=False),
    sa.Column('introduced_in_version', sa.Integer(), nullable=False),
    sa.Column('removed_in_version', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['concept_nodes.id'], name=op.f('fk_concept_edges_node_id_concept_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prereq_id'], ['concept_nodes.id'], name=op.f('fk_concept_edges_prereq_id_concept_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_concept_edges_subject_id_subjects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_concept_edges')),
    sa.UniqueConstraint('subject_id', 'prereq_id', 'node_id', name='uq_concept_edges_subject_pair')
    )
    with op.batch_alter_table('concept_edges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_concept_edges_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index('ix_concept_edges_subject_live', ['subject_id', 'deleted_at'], unique=False)

    op.create_table('mastery_records',
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('node_id', sa.String(length=36), nullable=False),
    sa.Column('mastery', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('direct_observations', sa.Integer(), nullable=False),
    sa.Column('indirect_observations', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decayed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['concept_nodes.id'], name=op.f('fk_mastery_records_node_id_concept_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_mastery_records_subject_id_subjects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mastery_records')),
    sa.UniqueConstraint('node_id', name='uq_mastery_records_node_id')
    )
    with op.batch_alter_table('mastery_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mastery_records_subject_id'), ['subject_id'], unique=False)

    op.create_table('plan_units',
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('node_id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('interleaved_node_ids', sa.JSON(), nullable=False),
    sa.Column('first_acquisition', sa.Boolean(), nullable=False),
    sa.Column('placement_reason', sa.Text(), nullable=False),
    sa.Column('priority', sa.Float(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_check_item_ids', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['concept_nodes.id'], name=op.f('fk_plan_units_node_id_concept_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['lesson_plans.id'], name=op.f('fk_plan_units_plan_id_lesson_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_plan_units_subject_id_subjects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_units')),
    sa.UniqueConstraint('plan_id', 'seq', name='uq_plan_units_plan_seq')
    )
    with op.batch_alter_table('plan_units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_units_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_units_subject_id'), ['subject_id'], unique=False)

    op.create_table('quiz_items',
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('node_id', sa.String(length=36), nullable=False),
    sa.Column('item_format', sa.String(length=24), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('stem', sa.Text(), nullable=False),
    sa.Column('choices', sa.JSON(), nullable=False),
    sa.Column('correct_choice', sa.Integer(), nullable=True),
    sa.Column('answer_key', sa.Text(), nullable=False),
    sa.Column('rubric', sa.Text(), nullable=False),
    sa.Column('cache_key', sa.String(length=200), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['concept_nodes.id'], name=op.f('fk_quiz_items_node_id_concept_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_quiz_items_subject_id_subjects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quiz_items')),
    sa.UniqueConstraint('cache_key', name='uq_quiz_items_cache_key')
    )
    with op.batch_alter_table('quiz_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_items_node_id'), ['node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_items_subject_id'), ['subject_id'], unique=False)

    op.create_table('review_cards',
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('node_id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('stability', sa.Float(), nullable=False),
    sa.Column('difficulty', sa.Float(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('lapses', sa.Integer(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('scheduled_days', sa.Float(), nullable=False),
    sa.Column('acquisition_step', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['concept_nodes.id'], name=op.f('fk_review_cards_node_id_concept_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_review_cards_subject_id_subjects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_cards')),
    sa.UniqueConstraint('node_id', name='uq_review_cards_node_id')
    )
    with op.batch_alter_table('review_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_cards_due_at'), ['due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_cards_subject_id'), ['subject_id'], unique=False)

    op.create_table('item_responses',
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('node_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('raw_answer', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('mastery_before', sa.Float(), nullable=True),
    sa.Column('mastery_after', sa.Float(), nullable=True),
    sa.Column('propagation', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['quiz_items.id'], name=op.f('fk_item_responses_item_id_quiz_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['concept_nodes.id'], name=op.f('fk_item_responses_node_id_concept_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_item_responses_subject_id_subjects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_responses'))
    )
    with op.batch_alter_table('item_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_responses_node_id'), ['node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_responses_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_responses_subject_id'), ['subject_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_responses_subject_id'))
        batch_op.drop_index(batch_op.f('ix_item_responses_session_id'))
        batch_op.drop_index(batch_op.f('ix_item_responses_node_id'))

    op.drop_table('item_responses')
    with op.batch_alter_table('review_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_cards_subject_id'))
        batch_op.drop_index(batch_op.f('ix_review_cards_due_at'))

    op.drop_table('review_cards')
    with op.batch_alter_table('quiz_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_items_subject_id'))
        batch_op.drop_index(batch_op.f('ix_quiz_items_node_id'))

    op.drop_table('quiz_items')
    with op.batch_alter_table('plan_units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_units_subject_id'))
        batch_op.drop_index(batch_op.f('ix_plan_units_plan_id'))

    op.drop_table('plan_units')
    with op.batch_alter_table('mastery_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mastery_records_subject_id'))

    op.drop_table('mastery_records')
    with op.batch_alter_table('concept_edges', schema=None) as batch_op:
        batch_op.drop_index('ix_concept_edges_subject_live')
        batch_op.drop_index(batch_op.f('ix_concept_edges_subject_id'))

    op.drop_table('concept_edges')
    with op.batch_alter_table('changeset_ops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_changeset_ops_changeset_id'))

    op.drop_table('changeset_ops')
    with op.batch_alter_table('study_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_sessions_subject_id'))
        batch_op.drop_index(batch_op.f('ix_study_sessions_scheduled_for'))

    op.drop_table('study_sessions')
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lessons_unit_id'))
        batch_op.drop_index(batch_op.f('ix_lessons_subject_id'))
        batch_op.drop_index(batch_op.f('ix_lessons_node_id'))

    op.drop_table('lessons')
    with op.batch_alter_table('lesson_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lesson_plans_subject_id'))

    op.drop_table('lesson_plans')
    with op.batch_alter_table('graph_suggestions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_graph_suggestions_subject_id'))
        batch_op.drop_index(batch_op.f('ix_graph_suggestions_dedupe_key'))

    op.drop_table('graph_suggestions')
    with op.batch_alter_table('diagnostic_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diagnostic_sessions_subject_id'))

    op.drop_table('diagnostic_sessions')
    with op.batch_alter_table('concept_nodes', schema=None) as batch_op:
        batch_op.drop_index('ix_concept_nodes_subject_live')
        batch_op.drop_index(batch_op.f('ix_concept_nodes_subject_id'))

    op.drop_table('concept_nodes')
    with op.batch_alter_table('changesets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_changesets_subject_id'))

    op.drop_table('changesets')
    op.drop_table('subjects')
    # ### end Alembic commands ###
